### ISSUE TITLE
ES: prevent unnecessary indexing

### ISSUE THREAD

**Issue by odanoburu** [own-pt/sensetion.el#102]
there is no need for elasticsearch to index most fields, e.g., we (currently) have no use for queries on the form of a token (only its lemma), nor do we need to query the original text of the sentence.

**Comment by arademaker** [comment]
this is optimization, low priority.

**Comment by arademaker** [comment]
actually it is good to have the option to search in forms and sentence. One can look for constructions

**Comment by odanoburu** [comment]
> actually it is good to have the option to search in forms and sentence. One can look for constructions

indeed, but while these are not implemented there is no need for indexing them. it might be a way of interfacing for #99
