### ISSUE TITLE
ES: retrieve sentences in stable order

### ISSUE THREAD

**Issue by odanoburu** [own-pt/sensetion.el#104]
elasticsearch returns results by default on its index order, which defaults to FIFO behaviour. this means that when we annotate a sentence in a session, close the session, and restart it, the sentence then appears as the last one. it is desirable however to have sentences show up in the same order.

**Comment by arademaker** [comment]
desirable ?! We had discussed that having it would make easier other implementations. This is a kind of thing that should be an option in the config. What is the criteria for sorting the sentences in the annotation buffer... we may have many.

**Comment by odanoburu** [comment]
> We had discussed that having it would make easier other implementations. 

no, that's what #101.

this is just how ES returns the results by default; I think we agreed that this default is not good for our purposes. but we can implement other sorting methods either in ES queries or in elisp.

**Comment by arademaker** [comment]
Sorry, I remember the discussion about #101 that things can be more natural if we don't have the movements of sentences. BTW, the last conversation with @alessandracid we agreed that move sentence can be useful during data consolidation. So maybe is better to keep that functionality.

**Comment by odanoburu** [comment]
> can be useful during data consolidation

but how? can this be done by sorting by some feature of the sentences? there is not much use in sorting manually because the order is lost as soon as the buffer is closed.

**Comment by arademaker** [comment]
One possible ideia is to put that feature in the clustered buffer, the one that cluster sentences by senses of a given word

For the sequencial annotation of corpora we  need to star some experiment to see what we will need

**Comment by odanoburu** [comment]
stale
