### ISSUE TITLE
ES: no annotation prevents buffer from closing

### ISSUE THREAD

**Issue by odanoburu** [own-pt/sensetion.el#105]
when a buffer is closed it triggers the creation of the annotation diff, showing what was changed in the annotation session. because there is no check of whether there were any changes, the diff creation raises an error.

**Comment by arademaker** [comment]
Let us try to be much more precise about what is the issue about? I don't see the diff creation as an important feature. At least not now considering that we are blocked because other more important issues.

**Comment by odanoburu** [comment]
> Let us try to be much more precise about what is the issue about?

this feature is implemented as follows:

- all sentences that are edited by the user are saved to disk in a file corresponding to the current annotation session.
- when the annotation session is over (i.e., the buffer is closed), a hook that creates the diff is triggered.
- the hook then opens the file with the changed sentences, reads them, gets their updated versions from the ES cluster, and diffs them.

this issue was created because there was no check for the existence of the file with the changed sentences, and this raises an error, which is fixed in https://github.com/own-pt/sensetion.el/commit/34f3cf4115496558573072ed2c6fa95ea267491d.

> I don't see the diff creation as an important feature. 

I see it as a way of avoiding the pitfalls described in #106; it's the diff functionality that we arguably want from a git repository, but implemented this way it's simpler and more efficient.

**Comment by arademaker** [comment]
I prefer not to rely on hooks, any other emacs crash can interrupt the normal workflow. The process you described is not very robust and it is time-consuming. If we take ES to be our DB, we must trust it to keep data integrity. We can test it if needed or try another option: use another backend with transaction support. Diff can be done from data in the repo compared to the data exported from the backend.
