### ISSUE TITLE
ES: save documents to disk

### ISSUE THREAD

**Issue by odanoburu** [own-pt/sensetion.el#106]
some users may want to store data directly in disk, e.g., using a git repo. We may:

1. save documents from ES to disk (the conversion doesn't seem trivial: [snapshots](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-snapshots.html) are not quite appropriate, as they are meant to be read by ES itself; and because of ES's retrieval limit, we would have to use the scroll API or python's elasticsearch client which abstracts it)
2. save documents from emacs to disk - but this negates some of the benefits of using ES; I don't see that much performance improvement, but the code became simpler. with this change, we might be looking at a slower and more complex tool.

**Comment by arademaker** [comment]
I believe option (1) above is unavoidable.
