### ISSUE TITLE
navigation: next/previous in the tagged mode

### ISSUE THREAD

**Issue by arademaker** [own-pt/sensetion.el#121]
In the master branch, the target mode. When annotating a MWE, moving next or previous should move to the next MWE not to the next/previous token part of the current MWE.

**Comment by odanoburu** [comment]
I see your point, but sometimes we want to move between tokens -- think of the case when you have a word in two globs, and you need to move to another token to be able to unglob the glob you want to unglob. we could have another command, but I don't like the solution in terms of UX...

**Comment by arademaker** [comment]
UX? Another command would be confusing and for your case we can use the normal commands from emacs to move between words.
