### ISSUE TITLE
dev: sequential mode not list sentences in order

### ISSUE THREAD

**Issue by arademaker** [own-pt/sensetion.el#133]
The sentences are not listed in the original order of the text in the sequencial mode, once a document is selected

**Comment by odanoburu** [comment]
tbh I don't know why this was happening, but the sentences were to be sorted by ES (which should be much faster). this is done by adding a sort parameter to the query -- why it's not working we'll have to investigate. https://github.com/own-pt/sensetion.el/commit/b4bccf348cad80be2bd2c64636adc29a62de06dc introduces a second sorting on elisp.  ideally we'd only have one sorting, and probably the elasticsearch one, so I'm reopening.

**Comment by odanoburu** [comment]
fixed by https://github.com/own-pt/sensetion.el/commit/92ec55c24eb65bce5ca17d7bdcf12f4cbb584a9c

elasticsearch was sorting the sentences lexicographically instead of numerically.

**Comment by arademaker** [comment]
I agree that best solution is to retrieve the sentences in the right order delegating to the ES the sorting.

**Comment by hmuniz** [comment]
We already delegating to the ES the sorting.
