### ISSUE TITLE
dev: command `c` not working

### ISSUE THREAD

**Issue by arademaker** [own-pt/sensetion.el#137]
in the sensetion buffer, sequential mode, `s` calls the menu, the `c` option is not working.

**Comment by arademaker** [comment]
in the sequential mode, a message must show the commad is not available and the menu (s) should not list it.

**Comment by hmuniz** [comment]
afcb53f8d4bebee2983e7ac220abe259498fd58b now it shows a message in sequencial mode that you already are in the context
