### ISSUE TITLE
dev: ignore/unignore 

### ISSUE THREAD

**Issue by arademaker** [own-pt/sensetion.el#138]
The `i` command should be a flag that one can call to ignore and call again to unignore..

**Comment by hmuniz** [comment]
It is import to say that if you ignore a token you will lose the senses annotations, unignore won't restore the annotations  removed by ignore

**Comment by arademaker** [comment]
@odanoburu the question is if the senses should be preserved or not once the user change to ignore. The problem of keeping the senses is that one could find difficult to interpret the data with ignore + senses.

**Comment by odanoburu** [comment]
I see :thinking:  I've added a confirmation to prevent reckless use of this command, but I think it should remove them.

**Comment by arademaker** [comment]
Yep. I tend to agree. Once the user confirm, better remove to make the data easy to interpret. Otherwise, nobody would no what was done first: the ignoring or the sense annotation.
