### ISSUE TITLE
dev: identify sentences

### ISSUE THREAD

**Issue by arademaker** [own-pt/sensetion.el#139]
In the target mode, it should be easy to identify the document containing the sentence. Maybe adding a tuple `(doc id, sent id)` before the sentence text.

~~Ideally, a user could put the cursor on the doc id and easily open a buffer with the document in the sequential mode.~~ (already implemented in the `c` command)

**Comment by arademaker** [comment]
target mode the sentences must be listed order by doc and sentence id.

**Comment by hmuniz** [comment]
Now the sentences in target mode are listed ordered by doc and sentence id and the tuple that identify the sentence it is already implemented too. You can turn off the sentence indication modifying the `sensetion-identify-sentence` variable.

**Comment by arademaker** [comment]
Once I annotated a token in a sentence, the doc/sent id tuple disapear.

**Comment by odanoburu** [comment]
> Maybe adding a tuple (doc id, sent id) before the sentence text.

this seems pretty distracting -- how did it turn out in the end? maybe end of the sentence is less distracting, or have it appear in the minibuffer after a timeout

**Comment by arademaker** [comment]
This is the kind of situation to solve interactively testing the options. I don’t think that it would be useful in the end of the sentences. It is good to easily see how far are two sentences in the original document and how is the target token distributed over the documents
