### ISSUE TITLE
dev: relax and restrict mode

### ISSUE THREAD

**Issue by hmuniz** [own-pt/sensetion.el#141]
For now, we cant write a lemma to a token or glob if that lemma is not part of wordnet.
In some projects, we need alow that. So it is important to create a restrict and a relax mode.

**Comment by arademaker** [comment]
I couldn't glob `Late Cretaceous`

**Comment by hmuniz** [comment]
9b183cef7d947a9250fdbb26a923eb803fc4a040 should implement the option to toggle the lemma restriction. To switch between relax and restrict mode you need to customize `Sensation Restrict Lemmas` variable. When you add a lemma in relax mode that is not in wn and contains a space you need to quote it: `C-q <space>` to really enter a space instead try completing.

See:
https://stackoverflow.com/questions/17473478/how-to-enter-a-space-in-the-minibuffer-instead-of-completing-a-word

**Comment by arademaker** [comment]
@odanoburu , did you check this implementation? code review please.

**Comment by odanoburu** [comment]
we have done a code review, yes!

**Comment by arademaker** [comment]
We need to document how to configure the modes in the use-package command. Maybe it is time to start wikipages with documentations

**Comment by odanoburu** [comment]
I've added documentation about customization in 270661d678437cac777931a4335050ece8978f56

**Comment by arademaker** [comment]
README file? I asked to start to use the wiki! We will need to start to take documentation seriously.

**Comment by odanoburu** [comment]
keeping documentation up-to-date is much easier when it's close to the source code and under version control. plus every user reads the README file, most don't even know the wiki option. 

if you want I can change it, but I find it more likely that it will become outdated.

another issue is that while we don't have a unified version a common wiki is recipe for confusion.

**Comment by arademaker** [comment]
A single README will not scale. wikis in githubb are under version control too. But fine if we start another org file with documentation.
