### ISSUE TITLE
[dev] [sequential] not showing sense number as superscript

### ISSUE THREAD

**Issue by arademaker** [own-pt/sensetion.el#143]
annotating north, chose north%n and sense 4, finish. The buffer does not show the superscript 4.

**Comment by arademaker** [comment]
I can't reproduce the error anymore.

**Comment by arademaker** [comment]
in the sequential mode the problem appears.

**Comment by odanoburu** [comment]
> in the sequential mode the problem appears.

this is by design, actually. i don't think we reached on a consensus on what to do here.. just showing an index doesn't make much sense in sequential mode, ref #99

**Comment by odanoburu** [comment]
closing this in favor of #145
