### ISSUE TITLE
dev: annotation of globs

### ISSUE THREAD

**Issue by arademaker** [own-pt/sensetion.el#144]
I have glob many `North Sea`. I tried to sense annotate them in another buffer. Search did not find sentences with `North Sea` lemma...

**Comment by arademaker** [comment]
Something is really wrong in the globs. I can't annotate globs in the sequential mode.

**Comment by hmuniz** [comment]
de9c56c0f6da55ce786af8db3406dae413ca8eae should solve the problem of annotation of globs. It is important to generate `synsets.json` again. If you don't want to do that I already update the  `synsets.json` available on box.

```lisp
CL-USER> (load "/home/hmuniz/sites/sensetion.el/json-convert.lisp")
T
CL-USER> (main "plist/" "new-synsets.json")
NIL
```
I am going to close this issue for now. If anyone find any problem reopen it, please.

**Comment by arademaker** [comment]
@hmuniz this also requires the update of the Elastic Search, the current make file would lose all annotations cleaning both indexes. So the solution you are proposing force us to rethink the current way to interact of the ES. 

- [ ] we need a code to dump de ES to text files for safety (conlllu like?)
- [ ] we need a better way to interact with ES (possible using the emacs restclient-mode to update only one index.

Finally, the dependencies are not clear. The `plist/` directory above is probably the `data` folder from the https://github.com/own-pt/glosstag repository, right? But this is not very clear nor ideal.

**Comment by hmuniz** [comment]
No, the current Makefile does not force us to lose all annotations. To update te index `sensetion-synsets` run:
`make synsets`

**Comment by hmuniz** [comment]
Sorry, `make synsets` would lose all annotations cleaning both indexes

**Comment by arademaker** [comment]
please explain why you are closing.

**Comment by odanoburu** [comment]
>  we need a code to dump de ES to text files for safety (conlllu like?)

we have `utils/es-dump.py`

> we need a better way to interact with ES (possible using the emacs restclient-mode to update only one index.)

we've updated the restclient file in the repository to be able to do this in 92ec55c24eb65bce5ca17d7bdcf12f4cbb584a9c
