### ISSUE TITLE
status bar numbers no sense

### ISSUE THREAD

**Issue by arademaker** [own-pt/sensetion.el#146]
what is the interpretation of the status bar `(sensetion: X/Y)` ? What is X? What is Y?

**Comment by hmuniz** [comment]
https://github.com/own-pt/sensetion.el/blob/e30f051fb49bcb3404817eb2b9829041969be0d1/sensetion.el#L135-L140

So X is the number of tokens annotated so far, and the Y is the number of annotatable tokens.

**Comment by arademaker** [comment]
if that is the case, we have a bug. annotating concentration in the target mode, I have 86/431. But all of the listed sentences, the word concentration was annotated (green).

another case, `ridge`, buffer shows `3/23` but only one sentence with one word.
