### ISSUE TITLE
update the current buffer

### ISSUE THREAD

**Issue by arademaker** [own-pt/sensetion.el#147]
related to #139, if annotating a buffer a jump to other buffer and annotate some tokens. When I close and return to an open buffer, I need a command to update the buffer, something like a `g` key.

**Comment by arademaker** [comment]
related to #137 , the jump is already implemented

**Comment by hmuniz** [comment]
`g` key already is bind to `sensetion-glob`, any other suggestion to the key bind for update current buffer?

**Comment by arademaker** [comment]
Maybe r for refresh

**Comment by hmuniz** [comment]
I am implementing this feature now. What is the desired effect when we update the current buffer, the tokens that were annotated in this session should become green or they should still blue? The question is when the buffer is updated is it a new session?

**Comment by arademaker** [comment]
no. refreshing a buffer is not creating a new one.

**Comment by hmuniz** [comment]
OK. For now, the refresh lost information about tokens annotated in the current session I will work to improve that.

**Comment by hmuniz** [comment]
Why are we interested in refresh all the buffer and not only a particular sentence?

**Comment by arademaker** [comment]
We may need many low-level commands, and update a sentence can be one of those. But I believe we need a buffer refresh too. Annotations on another buffer may affect many sentences. Think about a possible search refinement that lists in another buffer a subset of sentences in a current buffer. Once the user finishes the work on the subset, the current buffer may have many sentences affected.

**Comment by odanoburu** [comment]
I think this has been implemented, just not as a command. not sure if only
available at master though..

**Comment by odanoburu** [comment]
closing this and opened #153
