### ISSUE TITLE
dev: docs index should be a parameter

### ISSUE THREAD

**Issue by hmuniz** [own-pt/sensetion.el#150]
The corpus' index should not be hardcoded:
```
sensetion-client.el
68   	 (hits  (sensetion--es-query "sensetion-docs/_search"
92      (sensetion--es-request (format "sensetion-docs/_doc/%s" sent-id))
113  	 (hits  (sensetion--es-query "sensetion-docs/_search"
128  	 (hits (sensetion--es-query "sensetion-docs/_search"
140  	 (hits (sensetion--es-query "sensetion-docs/_search"
163      (sensetion--es-request (format "sensetion-docs/_doc/%s" (sensetion--sent-id sent))
```
Replace all occurrences of `sensetion-docs` by a custom variable solves that problem, probably with that we can switch between corpus easily.

**Comment by odanoburu** [comment]
this has been fixed by @hmuniz when implementing mongodb as a backend defined by a structure. a call to `sensetion-make-mongo` sets the collection name
