### ISSUE TITLE
customisation: show lexicographer file

### ISSUE THREAD

**Issue by arademaker** [own-pt/sensetion.el#155]
In the sense menu, I would like to have an option to show the lexicographer file in the senses list

<img width="1197" alt="image" src="https://user-images.githubusercontent.com/86403/63170038-ba594b00-c00e-11e9-9f1d-799bd1fe68b9.png">

Showing the `noun.person` in the list of synsets would make easier to identify the senses. Note that I am asking for a configuration option, not to make it hard coded.

**Comment by odanoburu** [comment]
this can be done by setting `sensetion-sense-menu-show-lexicographer-filename` to `t` in the `dev` branch.

**Comment by arademaker** [comment]
Precisamos manter documentação com todos estes parâmetros documentação. 

Por favor não deixe acumular. 

Sent from my iPhone
