### ISSUE TITLE
Convert glosstag data to json format

### ISSUE THREAD

**Issue by hmuniz** [own-pt/sensetion.el#161]
In the way of make the `dev` branch the principal, it is important to migrate the glosstag annotation to it so we need to convert the glosstag data to the JSON format.

**Comment by hmuniz** [comment]
The following script should do the job.
https://gist.github.com/hmuniz/9ff455e150e76e5c21ab97aad467f1b0

If you are using MongoDB first you should generate the data and then index it.
- Creating:
```lisp
CL-USER> (load "plist->json.lisp")

CL-USER> (main (directory "~/glosstag/data/*.plist") "~/sensetion.el/data/mongo/glosstag.json" 'mongo)
NIL
```
- Indexing:
```bash
python3 inject-mongodb.py ../data/mongo/synsets-mongo.json ../data/mongo/glosstag.json
```

**Comment by odanoburu** [comment]
script is now at `utils/convert-glosstag.lisp` (and may move to a glosstag-specific repository in the future)
