### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by arademaker** [own-pt/sensetion.el#190]
<img width="1347" alt="image" src="https://user-images.githubusercontent.com/86403/120017207-faa77480-bfbb-11eb-8db4-afad40e7e5f0.png">

cannot open load file?! messages 

```
eval-buffer: Cannot open load file: No such file or directory, request
```

**Comment by odanoburu** [comment]
that's a missing dependency, I believe! are the installation instructions incomplete, perhaps?

**Comment by arademaker** [comment]
yes, the `request` package was missing.
