### ISSUE TITLE
brew wn 

### ISSUE THREAD

**Issue by arademaker** [own-pt/sensetion.el#35]
https://github.com/Homebrew/homebrew-core/blob/master/Formula/wordnet.rb

it is not clear if the dbfiles are used, so downgrade to 3.0 may be not easier as it appears to be. It would be important to make clear your dependency to wn utility.

**Comment by odanoburu** [comment]
> It would be important to make clear your dependency to wn utility.
 
isn't it clear [here](https://github.com/own-pt/sensetion.el#installation)?

> it is not clear if the dbfiles are used, so downgrade to 3.0 may be not easier as it appears to be.

sorry, not 100% sure of what you mean; what steps did you take? did you have any problems?

**Comment by arademaker** [comment]
see #41 ,  the use of WNSEARCHDIR solves it.
