### ISSUE TITLE
how to fix tokenization

### ISSUE THREAD

**Issue by arademaker** [own-pt/sensetion.el#44]
The sentence below should be `can`+ `not`?

> afford | be able to spare or agive aup ; I ca n't afford to spend two hours with this personn1 ;

**Comment by arademaker** [comment]
Wow! It seems to be the tokenization adopted by PTB:

```
r$ ./ace -g erg.dat -E
I can't afford to spend two hours with this person.
I ca n’t afford to spend two hours with this person .
```

**Comment by odanoburu** [comment]
yep.. do you think we should change it? or should we close this?

**Comment by arademaker** [comment]
for this case, we do nothing. but we can edit the source for errors in tokenization and POS tagging. Related to #45
