### ISSUE TITLE
more than one sense

### ISSUE THREAD

**Issue by arademaker** [own-pt/sensetion.el#56]
I want to be able to annotate more than one sense in a token or glob

**Comment by odanoburu** [comment]
when we had only one sense we made the token lemma that of the sense after the annotation; how should I handle it now? is there a case where we might be unsure between senses of different pos and/or lemma?

**Comment by arademaker** [comment]
I don't think we should change the token lemma. The lemma `word%POS` should be considered the pre-annotation information, given by a data preparation tool, the options that restrict the annotator options for the senses. We only touch in the senses. In the future, new processing over the files can add/remove lemmas, that would sign the necessity of sense reannotation. 

This is a conversative approach; we don't throw away any information. The final data can be read as `over these set of possible `lemma%POS`, the human choose the X sense.  Of course, `bank%1` is an example of a word with multiple senses for the same POS tag. So keep this information only says that `bank%1` was an option in that context when the human choose X sense.

What do you think?

**Comment by arademaker** [comment]
Note also that any annotation should be subject of revision. If you remove the possible `lemma%POS` from the list, one can't get back that context when repeating a query in the interface.
