### ISSUE TITLE
remove sense

### ISSUE THREAD

**Issue by arademaker** [own-pt/sensetion.el#60]
During the annotation of `formation`:

(n) male bonding | the formation`n6,3` of a close apersonal arelationship between men ; the rituals known as bmale bbonding do not necessarily involve drinking beer together ;

In the new version, using the letters/numbers we can add more than one sense per token. How to remove senses? In the sentence above, I want to remove the sense 6.

**Comment by odanoburu** [comment]
a hack that will work for now is to choose `[0] no sense in wordnet` and then call the editing command again to add the actual annotation.

**Comment by odanoburu** [comment]
my problem with removing senses one-by-one is that we may implicitly be getting into the "no sense in wordnet" annotation. this becomes a problem if we really make the annotation field be either a pos string (for when there's no sense) or a non-empty list, because we might end up with an empty list. not sure what's the best way out though..

**Comment by arademaker** [comment]
I am not sure either. I didn't like the idea of keeping a single string in the sense list to mark only the pos. I don't see value on that. But if we really choose to have that information, maybe is better to have some other field. 

In that case, status `man` and empty list of senses would have the meaning `no sense in PWN` but I would still prefer something more explicit.

**Comment by odanoburu** [comment]
so we can add a `nosense` tag for tokens with no sense, and a clear option that would make the token behave as if untagged -- no sense annotation and tag becomes `un`? then the user can add new senses if they want; but if they want to remove a sense, they have to remove all senses with clear, and then add back the senses they want.

**Comment by arademaker** [comment]
I didn’t understand the last comment
