### ISSUE TITLE
showing POS tags before senses to annotate

### ISSUE THREAD

**Issue by arademaker** [own-pt/sensetion.el#61]
during `personal` annotation, once I press `/` I get a list of POS tags to select the list of senses to annotate. `personal` is a case with 5 senses, being 4 adj. Does it make sense to allow `all` here? Anyway, even if we choose not to have `all`, we need some way to say 

- no sense in PWN
- I dont know

**Comment by arademaker** [comment]
note that `no sense` is shown only after POS tag selection, but it doesn't make sense, right?

**Comment by odanoburu** [comment]
> we need some way to say - no sense in PWN - I dont know

I want us to decide how to encode this in the data at #58, so that I can implement it!

what do you mean by `all`?

**Comment by arademaker** [comment]
all would means `list all senses from all POS` but we decided not to have this opitions.
