### ISSUE TITLE
know which annotator tagged something?

### ISSUE THREAD

**Issue by odanoburu** [own-pt/sensetion.el#62]
it would be nice to know who annotated what.

however there's no easy and simple solution to this problem -- if we add a sense as an alist of sense-annotator, the code gets more complicated, and we still might have problems if an annotator removes a sense from another and then adds it back again. a real solution would involve triples of (add sense annotator) and (delete sense annotator), but that would be even more complicated.

so maybe just keep things as they are...

**Comment by arademaker** [comment]
So far, we agree that annotation is an individual task over a set of files, a corpus, and we can delegate the IAA evaluation to another tool. Should we close this issue?

**Comment by odanoburu** [comment]
yes, it is here just for documentation purposes!
