### ISSUE TITLE
annotating `rock`

### ISSUE THREAD

**Issue by arademaker** [own-pt/sensetion.el#67]
glosses with `rock star` do not show up anymore. I thought we agree on showing all glosses that have a given lemma, even if the tokens with that lemmas are part of globs. So the annotator could revise globs and unglob when necessary.

**Comment by arademaker** [comment]
related to #68

**Comment by odanoburu** [comment]
what happens at this point is that whenever a collocation is unglobbed we index the new lemma, but don't remove the old ones; however when indexing all files, the lemmas of the component tokens of a collocation do not get indexed.

I know we agreed to indexing the component tokens; but now that I see a way of removing the lemmas of the component tokens when globbing I'm not so sure what is the best way.

if we go forward with this we will be indexing `William` in `William Shakespeare` (which I think will rarely be up for revision), but also `go` in `go with`.

in the end this change would make revision faster, but I don't think it would change the ultimate results. 

on the one hand, it might be distracting in that when annotating `go` one would constantly find phrasal verbs and have to decide if they are indeed phrasal verbs or if they are actually instances of `go` that should be annotated.

on the other hand, it would also be frustrating to annotate all instances of `go` and then go after its phrasal verbs, revise them, and actually find out there are more instances of `go` to annotate. (however this disadvantage can probably be mitigated by intelligently choosing the order of annotation, i.e., going to our search interface, searching for `go`, and then doing all `go`-including phrasal verbs first.

**Comment by odanoburu** [comment]
we have decided to show all glosses that have a given lemma, even if its token is part of a collocation; this is implemented.
