### ISSUE TITLE
database format

### ISSUE THREAD

**Issue by arademaker** [own-pt/sensetion.el#71]
We choose to work with a `lisp-friendly` encoding of glosses as `plists`, but serialization between Emacs Lisp and Common Lisp differ. Not only in the identation, solved by a9bcaa4aff1dbf07ef4d141ea73e4cd4a23cad5c, but also in the order of the keys. See below the diff between two versions of a file changed during the edition where only the order of the keys differs. The diffs reflect not `semantic` changes but also `syntactic irrelevant changes`.

```
-  (:form "a" :lemma "a" :pos "DT" :anno nil :status "ignore" :kind :wf :meta
+  (:form "a" :lemma "a" :pos "DT" :status "ignore" :kind :wf :anno nil :meta
    ((:id "wf4")))
-  (:form "short" :lemma "short%1|short%2|short%3|short%4" :pos "JJ" :anno
-   ("a01442186" "a01436003") :status "man" :kind :wf :meta ((:id "wf5")))
-  (:form "distance" :lemma "distance%1|distance%2" :pos "NN" :anno
-   ("n05129565") :status "man" :kind :wf :meta ((:id "wf6")))
-  (:form "in" :lemma "in" :pos "IN" :anno nil :status "ignore" :kind :wf :meta
+  (:form "short" :lemma "short%1|short%2|short%3|short%4" :pos "JJ" :status
+   "man" :kind :wf :anno ("a01442186" "a01436003") :meta ((:id "wf5")))
+  (:form "distance" :lemma "distance%1|distance%2" :pos "NN" :status "man"
+   :kind :wf :anno ("n05129565") :meta ((:id "wf6")))
+  (:form "in" :lemma "in" :pos "IN" :status "ignore" :kind :wf :anno nil :meta
    ((:id "wf7")))
```

We need a text format that is human readable but also stable. Changes in the file should reflect semantic changes in the content and the editor should not make irrelevant changes. In that case, diffs can help debug and track work evolution (specially if a user want to use git for tracking the data directory).

Moreover, we need to find a better way to organize the data into files. Leaving all data files in the same directory is inefficient for many command line tools and SO. We can (1) split files into subdirectories, or (2) reduce the number of files having multiple glosses per file.

**Comment by arademaker** [comment]
The standoff directory in the glosstag distribution contains 

```
$ find . | wc -l
    8375
```

compared to the current db directory of plist files:

```
$ find . | wc -l
  117697
```

**Comment by odanoburu** [comment]
my ideal solution would be something like json-line, with all synsets of a given PoS sorted in the same file, but I'm not sure if that would work well enough; guess we will have to try and see.

**Comment by odanoburu** [comment]
based on my tests it seems that the different key order is due to different printing in common lisp and in elisp, but it can be fixed. If you'd like to be robust, I can do the convert-to-alist-and-sort thing when saving in case we forget about this and change the order (although I don't think we'll be changing the fields often or at all...)
