### ISSUE TITLE
reset token annotation when it is globbed?

### ISSUE THREAD

**Issue by odanoburu** [own-pt/sensetion.el#77]

**Comment by arademaker** [comment]
do you mean the annotation of senses, right? 

The alternative is to have one more `indirect` interpretation of the data. if a token has a sense and it is part of the glob, its sense is irrelevant and the glob token with the same coll holds the sense of the glob... right? the unique benefit of that is that we do not throw away any information.

**Comment by odanoburu** [comment]
> do you mean the annotation of senses, right?

yes!

yes, I think that's a good decision!
