### ISSUE TITLE
add status window

### ISSUE THREAD

**Issue by odanoburu** [own-pt/sensetion.el#8]
- [ ] keep track of missing tokens in current annotation iteration
- [ ] keep track of missing tokens in the whole corpus
- [ ] suggest new iterations (new lemmas)

**Comment by odanoburu** [comment]
I was thinking about doing the window idea and just adding an indicator to the mode-line; what do you think, @arademaker?

(I'm close to finishing the internal book-keeping, just need to decide how best to show it)

we have already decided that the annotation suggestion can be just a completion in the prompt, or would you rather have it somewhere else?

**Comment by arademaker** [comment]
hard to answer without more understanding about the options. Follow your intuition, having the first running version is more important now.

**Comment by odanoburu** [comment]
stale
