### ISSUE TITLE
in the list of senses, ident the second line of the synsets to facilitate the reading

### ISSUE THREAD

**Issue by arademaker** [own-pt/sensetion.el#82]

**Comment by arademaker** [comment]
I was expecting the next lines would be really aligned to the first char of the first line... Can we also have the synset ID listed after the numers (0, 1 ...) just for quickref to the online interface? That could also be a configuration flag (one can prefer not to have this info).

<img width="1317" alt="Screenshot 2019-03-29 10 17 09" src="https://user-images.githubusercontent.com/86403/55250751-2bd56000-520c-11e9-9b77-5f68ee55f095.png">

**Comment by odanoburu** [comment]
the variable is `sense-menu-show-synset-id`, you just have to set it to `t` as in my use-package declaration:

```elisp
(use-package sensetion
  :commands sensetion
  :load-path "~/work/sensetion/"
  :hook (sensetion-edit-mode . lispy-mode)
  :custom
  (sense-menu-show-synset-id t))
```
