### ISSUE TITLE
I can't remove the `unsure` 

### ISSUE THREAD

**Issue by arademaker** [own-pt/sensetion.el#83]
I want to press `?` again to remove this flag. unsure is marked if `unsure 0`? it should be 1? the colors didn't changed if I edited the source.

**Comment by odanoburu** [comment]
Now the command toggles the value of the `:unsure` field.

the values of this field used to be zero or one, but now it is a boolean, I've fixed that too. do you have your files in a public repo? I'll correct them.

> the colors didn't changed if I edited the source.

I've created #87 to fix this. the source edit is done but the buffer is not updated with this info.
