### ISSUE TITLE
when choose to annotate `deposit` and `noun` only the system ignored and list verb cases too

### ISSUE THREAD

**Issue by arademaker** [own-pt/sensetion.el#86]

**Comment by odanoburu** [comment]
sorry, I don't understand what this issue is about

**Comment by arademaker** [comment]
putting in another way , why the buffer `sensetion@n@deposit` is showing to me senses where `deposit` has POS VBP? I would expect it in the buffer `sensetion@any@deposit` only.

**Comment by odanoburu** [comment]
because sensetion considers the lemma/pos candidates, not the PoS tag assigned; in this case we probably have as lemma something like `deposit%1|deposit%2`.

**Comment by arademaker** [comment]
Thinking about it, what we actually have is always an implicit `any`. I believe that all lemmas are filled with ALL possible lemma/POS of the word in PWN.
