### ISSUE TITLE
not all senses were listed

### ISSUE THREAD

**Issue by arademaker** [own-pt/sensetion.el#88]
The adj `incompatible` has 9 senses but only 4 are listed in sensetion:

<img width="1689" alt="image" src="https://user-images.githubusercontent.com/86403/55624833-7a8b7880-577d-11e9-829a-9edec15ce5fd.png">

<img width="1447" alt="image" src="https://user-images.githubusercontent.com/86403/55624840-8119f000-577d-11e9-882f-61c1737bce90.png">

**Comment by odanoburu** [comment]
I've fixed this yesterday -- it was an instance of the synset type
primeness. please pull the changes and it will go away!

>
