### ISSUE TITLE
are sense indices stable?

### ISSUE THREAD

**Issue by odanoburu** [own-pt/sensetion.el#89]
(the ones that show in the hydra/editing menu)

**Comment by arademaker** [comment]
in the mini buffer (i am not sure the proper name) that list the synsets during the annotation.

**Comment by odanoburu** [comment]
the order depends on a `cl-loop`, which might always give the same results, but I wouldn't rely on it. the order of the indices can be made stable easily by sorting lexicographically on synset-id or sense key.

**Comment by arademaker** [comment]
Better make it stable and predictable.
