### ISSUE TITLE
autocomplete lemmas

### ISSUE THREAD

**Issue by arademaker** [own-pt/sensetion.el#91]
People's_Republic_of_China is a lemma in PWN

the autocomplete is not working. BTW, one step early I had globed this in 

(v) derecognise,derecognize,decertify | cause to be ano alonger approved or accepted ; Carter derecognized Taiwan in 1979 after the U.S. recognized the bPeople's bRepublic bof bChina ;

**Comment by odanoburu** [comment]
it seems to work here!

do note that `sensetion.el` doesn't show all completions at time (it by default shows 15 completions, and this can be changed by setting the variable `sensetion-number-completions`)

also note that completion is case-sensitive.

**Comment by arademaker** [comment]
Ah, ok

**Comment by odanoburu** [comment]
@arademaker I've updated the answer with more details (nothing you probably don't are already but it's good for documentation purposes).

there's also a fuzzy match offered by the underlying library, would you like to experiment with this?

**Comment by arademaker** [comment]
I don't understand the last comment @odanoburu
