### ISSUE TITLE
red colour was lost after mark for glob and undo mark.

### ISSUE THREAD

**Issue by arademaker** [own-pt/sensetion.el#95]

**Comment by odanoburu** [comment]
this can be fixed by moving to a transaction-based model, where the user tags several sentences and then confirms that they are final, which is when they get sent to the backend

**Comment by arademaker** [comment]
Sorry , I didn’t  understand

**Comment by odanoburu** [comment]
sorry, better not to refer to color since these are customizable. you mean that tokens annotated in the current session are not colored as such after mark-glob and undo glob-mark?

**Comment by arademaker** [comment]
Yep.

**Comment by odanoburu** [comment]
this is now fixed in https://github.com/own-pt/sensetion.el/commit/77f06deeb8fc90450c69328ed3baeb75da09d0f1 (`es` branch); tokens marked for globbing are now represented by an underline.
